### ISSUE TITLE
Player not support this device

### ISSUE THREAD

**Issue by Grovertb** [tcking/GiraffePlayer#13]
Hi, I'm using version 0.3 and I get this error Player not support this device . My device is a galaxy s5 . Prior 2.0 eh you used without problems.

**Comment by tcking** [comment]
can you show the stack trace please

**Comment by diaconuliviu85** [comment]
with version 4 , a friend gets this error. a nexus player. intel cpu . I still log but tomorrow I get it. I tested the Nexus 9 Nexus 6 , the shield nvidia tv without errors.

**Comment by diaconuliviu85** [comment]
E/GiraffePlayer: loadLibraries error
                                                                          java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/ro.vrt.videoplayerstreaming-1/lib/x86/libijkffmpeg.so: has text relocations

**Comment by diaconuliviu85** [comment]
this problem is found and vitamio and is currently a problem with no solution. sdk 22 only if we go well.

**Comment by tcking** [comment]
v0.4 has x86 so files，make sure the the so files in the apk after build,or try this:
``` javascript
1.add abiFilters in build.gradle:
android{
...
defaultConfig{

    //add this
    ndk {
        abiFilters "armeabi"
    }
}
}

2.add android.useDeprecatedNdk=true in gradle.properties
```

**Comment by diaconuliviu85** [comment]
yes ,  and from nexus player cpu intel and android 6.0.1  is not work
log :`02-22 18:21:12.176 6259-9852/ro.vrt.videoplayerstreaming W/cr_media: Requires BLUETOOTH permission
02-22 18:21:12.212 6259-6259/ro.vrt.videoplayerstreaming I/Ads: Starting ad request.
02-22 18:21:12.213 6259-6259/ro.vrt.videoplayerstreaming I/Ads: Use AdRequest.Builder.addTestDevice("F7317B922DCCFD09D20E6878B811383D") to get test ads on this device.
02-22 18:21:12.231 6259-6259/ro.vrt.videoplayerstreaming E/linker: /data/app/ro.vrt.videoplayerstreaming-2/lib/x86/libijkffmpeg.so: has text relocations
02-22 18:21:12.233 6259-6259/ro.vrt.videoplayerstreaming E/GiraffePlayer: loadLibraries error
                                                                          java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/ro.vrt.videoplayerstreaming-2/lib/x86/libijkffmpeg.so: has text relocations
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                              at java.lang.System.loadLibrary(System.java:1076)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:144)
                                                                              at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:155)
                                                                              at tcking.github.com.giraffeplayer.GiraffePlayer.<init>(GiraffePlayer.java:263)
                                                                              at ro.vrt.videoplayerstreaming.MainActivity.onCreate(MainActivity.java:76)
                                                                              at android.app.Activity.performCreate(Activity.java:6251)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-22 18:21:12.279 6259-6259/ro.vrt.videoplayerstreaming I/Ads: Starting ad request.`

**Comment by diaconuliviu85** [comment]
>         ndk {
>             abiFilters "armeabi", "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
>         }
We all "so" necessary.  and from android 6.0.1 cpu intel x86 not work , from nexus 9 cpu nvidia android 6.0.1 64bit is work from nexus 6 cpu snapdragon androis 6.0.1 is work .
and from cpu intel x86 bot android 5.1 is work fine.

**Comment by tcking** [comment]
that is the problem on android 6.0+ device,try modify the `build.grade` and lower the targetSdkVersion less than 23, that works for me on android 6.0 x86 emulator
``` javascript
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "tcking.github.com.giraffeplayer"
        minSdkVersion 10
        targetSdkVersion 21// lower than 23
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "armeabi","armeabi-v7a","arm64-v8a","x86","x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

**Comment by Parwinder7808** [comment]
Using Android Studio when i create **_Signed APK_** (working fine with non signed apk) and start Android App
below error occurs all the time.

ERROR
--------
Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/parwinder.singh.livekirtan-1/lib/arm/libvlcjni.so"

It happens only if i set minifyEnabled true. 

I have placed libvlcjni.so files in src->main->jniLibs->armeabi-v7a


buildTypes {
        release {
            minifyEnabled true;
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

proguard-rules.pro file
-------------------------
-keep public class org.videolan.libvlc.**
-keep public class com.squareup.picasso.**
-keep public class com.squareup.okhttp.**
-dontwarn com.squareup.picasso.**
-dontwarn com.squareup.okhttp.**
-keepclasseswithmembers class * {
    native <methods>;
}

**Comment by prudhvistream** [comment]
I'm also facing the problem like text relocations error as this in My Log

`E/GiraffePlayer: loadLibraries error
                                                                 java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.live.streamnow-Zil4ZLFNjsI0xQUuMMCJ9w==/lib/x86/libijkffmpeg.so" has text relocations`

**Comment by tcking** [comment]
you can let targetSdkVersion less then 23
or you can try [GiraffePlayer2](https://github.com/tcking/GiraffePlayer2)
