### ISSUE TITLE
who can help me 

### ISSUE THREAD

**Issue by philos3** [tcking/GiraffePlayer#23]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.philos.videoproject-1/lib/arm64/libijkffmpeg.so" is 32-bit instead of 64-bit
                                                                           untime.loadLibrary(Runtime.java:383)
                                                                           at java.lang.System.loadLibrary(System.java:998)
                                                                           at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:137)
                                                                           at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:148)
                                                                           at tcking.github.com.giraffeplayer.GiraffePlayer.<init>(GiraffePlayer.java:264)
                                                                           at com.philos.videoproject.VideoDetailActivity.onCreate(VideoDetailActivity.java:74)
                                                                           at android.app.Activity.performCreate(Activity.java:6013)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                                                                           at android.app.ActivityThread.access$1200(ActivityThread.java:158)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5564)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by tcking** [comment]
try using the latest version [0.5](https://github.com/tcking/GiraffePlayer/releases/tag/0.5)
