### ISSUE TITLE
在Fragment中无法播放

### ISSUE THREAD

**Issue by sendtion** [tcking/GiraffePlayer#52]
在ViewPager+Fragment中无法新建播放器，报错！
在Activity中正常，错误指示无法获取videoview的xml中的控件。

**Comment by tcking** [comment]
支持fragment，你需要在`onViewCreated`中初始化GiraffePlayer

**Comment by sendtion** [comment]
@tcking 我就是在onViewCreated中初始化的，GiraffePlayer初始化需要传入Activity，我使用getActivity传入不可行，或者有什么别的方法传入activity？

**Comment by tcking** [comment]
fragment加载的布局需要include `giraffe_player.xml`,在`onViewCreated `初始化传入`getActivity ()`就行

**Comment by sendtion** [comment]
@tcking 没错啊，我就是这样做的。
 
**fragment_tab_learning.xml**
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.bri.cdstm.ui.fragment.TabLearningFragment">

    <include
        android:id="@+id/player_learning"
        layout="@layout/giraffe_player"
        android:layout_width="match_parent"
        android:layout_height="200dp" />

    <com.jcodecraeer.xrecyclerview.XRecyclerView
        android:id="@+id/rv_list_learning"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/player_learning" />

</RelativeLayout>
`
**TabLearningFargment.java**
`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_tab_learning, null);
        //iv_learning_banner = (ImageView) view.findViewById(R.id.iv_learning_banner);
        rv_list_learning = (XRecyclerView) view.findViewById(R.id.rv_list_learning);
        player = new GiraffePlayer(getActivity());
}`

但是仍然报错。
videoView = (IjkVideoView) activity.findViewById(R.id.video_view);
videoView.setAspectRatio(IRenderView.AR_MATCH_PARENT);
在上面一句，videoview报空指针异常。应该是不能通过传过来的activity获得videoview。

**Comment by tcking** [comment]
注意，是在onViewCreated,不是onCreatView

**Comment by sendtion** [comment]
@tcking 仍然不行。

`@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        player = new GiraffePlayer(getActivity());
    }`

`View liveBox = activity.findViewById(R.id.app_video_box);
        liveBox.setClickable(true);`
这里报错，错误如下。

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setClickable(boolean)' on a null object reference
                                                                   at tcking.github.com.giraffeplayer.GiraffePlayer.<init>(GiraffePlayer.java:332)
                                                                   at com.bri.cdstm.ui.fragment.TabLearningFragment.onViewCreated(TabLearningFragment.java:134)`

**Comment by hisonedumobile** [comment]
@tcking @sendtion "fragment加载的布局需要include  giraffe_player.xml ,在 onViewCreated 初始化传入 getActivity () 就行"，我的项目中这样做以后，确实可以

**Comment by hisonedumobile** [comment]
@sendtion
我的xml文件：
<include
        layout="@layout/giraffe_player"
        android:layout_width="match_parent"
        android:layout_height="210dp"/>
我的fragment文件中：
@Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mVedioPlayer = new GiraffePlayer(this.getActivity());
        if (mVideoPath == "") {
            // Tell the user to provide a media file URL/path.
            Toast.makeText(
                    getActivity(),
                    "No Video Found! Press Back Button To Exit",
                    Toast.LENGTH_LONG).show();
        } else {
            mVedioPlayer.play(mVideoPath);
        }
    }

**Comment by DovSnier** [comment]
我在GiraffePlayer 类中扩展了一下,然后也可以的；

public GiraffePlayer(final Activity activity, final View view) {
        try {
            IjkMediaPlayer.loadLibrariesOnce(null);
            IjkMediaPlayer.native_profileBegin("libijkplayer.so");
            playerSupport = true;
        } catch (Throwable e) {
            Log.e("GiraffePlayer", "loadLibraries error", e);
        }
        this.activity = activity;
        screenWidthPixels = activity.getResources().getDisplayMetrics().widthPixels;
        $ = new Query(activity);
        videoView = (IjkVideoView) view.findViewById(R.id.video_view);
        videoView.setOnCompletionListener(new IMediaPlayer.OnCompletionListener() {
            @Override
            public void onCompletion(IMediaPlayer mp) {
                statusChange(STATUS_COMPLETED);
                oncomplete.run();
            }
        });
        videoView.setOnErrorListener(new IMediaPlayer.OnErrorListener() {
            @Override
            public boolean onError(IMediaPlayer mp, int what, int extra) {
                statusChange(STATUS_ERROR);
                onErrorListener.onError(what, extra);
                return true;
            }
        });
        videoView.setOnInfoListener(new IMediaPlayer.OnInfoListener() {
            @Override
            public boolean onInfo(IMediaPlayer mp, int what, int extra) {
                switch (what) {
                    case IMediaPlayer.MEDIA_INFO_BUFFERING_START: //TODO 缓冲开始
                        statusChange(STATUS_LOADING);
                        break;
                    case IMediaPlayer.MEDIA_INFO_BUFFERING_END: //TODO 缓冲结束
                        statusChange(STATUS_PLAYING);
                        break;
                    case IMediaPlayer.MEDIA_INFO_NETWORK_BANDWIDTH: //TODO 下载带宽
                        //显示 下载速度
//                        Toaster.show("download rate:" + extra);
                        break;
                    case IMediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START: //TODO 渲染画面
                        statusChange(STATUS_PLAYING);
                        break;
                }
                onInfoListener.onInfo(what, extra);
                return false;
            }
        });

        seekBar = (SeekBar) view.findViewById(R.id.app_video_seekBar);
        seekBar.setMax(1000);
        seekBar.setOnSeekBarChangeListener(mSeekListener);
        $.id(R.id.app_video_play).clicked(onClickListener);
        $.id(R.id.app_video_fullscreen).clicked(onClickListener);
        $.id(R.id.app_video_finish).clicked(onClickListener);
        $.id(R.id.app_video_replay_icon).clicked(onClickListener);


        audioManager = (AudioManager) activity.getSystemService(Context.AUDIO_SERVICE);
        mMaxVolume = audioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC);
        final GestureDetector gestureDetector = new GestureDetector(activity, new PlayerGestureListener());


        View liveBox = view.findViewById(R.id.app_video_box);
        liveBox.setClickable(true);
        liveBox.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                if (gestureDetector.onTouchEvent(motionEvent))
                    return true;

                // 处理手势结束
                switch (motionEvent.getAction() & MotionEvent.ACTION_MASK) {
                    case MotionEvent.ACTION_UP:
                        endGesture();
                        break;
                }

                return false;
            }
        });


        orientationEventListener = new OrientationEventListener(activity) {
            @Override
            public void onOrientationChanged(int orientation) {
                if (orientation >= 0 && orientation <= 30 || orientation >= 330 || (orientation >= 150 && orientation <= 210)) {
                    //竖屏
                    if (portrait) {
                        activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);
                        orientationEventListener.disable();
                    }
                } else if ((orientation >= 90 && orientation <= 120) || (orientation >= 240 && orientation <= 300)) {
                    if (!portrait) {
                        activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);
                        orientationEventListener.disable();
                    }
                }
            }
        };
        if (fullScreenOnly) {
            activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        }
        portrait = getScreenOrientation() == ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
        initHeight = view.findViewById(R.id.app_video_box).getLayoutParams().height;
        hideAll();
        if (!playerSupport) {
            showStatus(activity.getResources().getString(R.string.not_support));
        }
    }
