### ISSUE TITLE
正在加载视频，退出视频界面。屏幕点击无反应。

### ISSUE THREAD

**Issue by FDoubleman** [tcking/GiraffePlayer#68]
1、现象：当我点击进入play 界面时，视频进度正在加载状态。我再返回调用play 的界面时，屏幕点击没有反应 not response  。
2、如果是视频 加载成功，或者失败。退出就不会出现这种情况。求大神帮忙解决下！ 对了  我使用的是小米max做的测试

**Comment by tcking** [comment]
看看ANR日志里是否有有用的信息

**Comment by FDoubleman** [comment]
`E/ActivityManager: ANR in cn.wd.wdstudyonline (cn.wd.wdstudyonline/cn.wdcloud.studyonline.asphone.ui.activity.CourseLearnActivity)
                                                  PID: 17665
                                                  Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 6097.6ms.)
                                                  Load: 7.07 / 6.92 / 6.84
                                                  CPU usage from 856776ms to 0ms ago:
                                                    2.9% 527/adbd: 0.3% user + 2.5% kernel / faults: 110661 minor
                                                    2.6% 441/surfaceflinger: 1.6% user + 1% kernel / faults: 314 minor
                                                    2.2% 1160/system_server: 1.5% user + 0.6% kernel / faults: 26751 minor 6 major
                                                    1.3% 3083/com.android.systemui: 0.9% user + 0.3% kernel / faults: 9266 minor 9 major
                                                    1.2% 285/cfinteractive: 0% user + 1.2% kernel
                                                    0.8% 538/mediaserver: 0.7% user + 0.1% kernel / faults: 89 minor
                                                    0.3% 365/hwrng: 0% user + 0.3% kernel
                                                    0.3% 29795/mdss_fb0: 0% user + 0.3% kernel
                                                    0.2% 26810/com.xiaomi.gamecenter: 0.2% user + 0% kernel / faults: 7444 minor
                                                    0.2% 31150/com.android.browser: 0.2% user + 0% kernel / faults: 23635 minor
                                                    0.2% 386/logd: 0% user + 0.1% kernel / faults: 70 minor
                                                    0.2% 3795/com.android.phone: 0.1% user + 0% kernel / faults: 3234 minor
                                                    0.1% 31192/kworker/u12:8: 0% user + 0.1% kernel
                                                    0.1% 26873/kworker/u12:4: 0% user + 0.1% kernel
                                                    0.1% 7/rcu_preempt: 0% user + 0.1% kernel
                                                    0.1% 45/kworker/u13:0: 0% user + 0.1% kernel
                                                    0.1% 20258/com.tencent.mobileqq:MSF: 0.1% user + 0% kernel / faults: 1738 minor
                                                    0.1% 440/servicemanager: 0% user + 0% kernel / faults: 8 minor
                                                    0.1% 11641/com.xiaomi.market: 0.1% user + 0% kernel / faults: 3128 minor
                                                    0.1% 3031/VosRXThread: 0% user + 0.1% kernel
                                                    0.1% 11734/com.tencent.mobileqq:web: 0% user + 0% kernel / faults: 2124 minor
                                                    0.1% 3030/VosTXThread: 0% user + 0.1% kernel
                                                    0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
                                                    0% 6484/kworker/0:1: 0% user + 0% kernel
                                                    0.1% 3353/wpa_supplicant: 0% user + 0% kernel / faults: 1 minor
                                                    0% 327/irq/412-ft5x46: 0% user + 0% kernel
                                                    0% 3682/com.miui.whetstone: 0% user + 0% kernel / faults: 199 minor
                                                    0% 763/msm_irqbalance: 0% user + 0% kernel / faults: 1 minor
                                                    0% 3274/com.miui.networkassistant.deamon: 0% user + 0% kernel / faults: 365 minor
                                                    0% 5191/irq/215-408000.: 0% user + 0% kernel
                                                    0% 25169/kworker/3:1: 0% user + 0% kernel
                                                    0% 12/ksoftirqd/1: 0% user + 0% kernel
                                                    0% 20/ksoftirqd/3: 0% user + 0% kernel
                                                    0% 68/system: 0% user + 0% kernel
                                                    0% 29801/logcat: 0% user + 0% kernel
                                                    0% 31179/kworker/u12:5: 0% user + 0% kernel
                                                    0% 4607/com.miui.powerkeeper:service: 0% user + 0% kernel / faults: 6293 minor
                                                    0% 3029/VosMCThread: 0% user + 0% kernel
                                                    0% 3361/com.miui.home: 0% user + 0% kernel / faults: 3383 minor 4 major
                                                    0% 551/thermal-engine: 0% user + 0% kernel
                                                    0% 289/mmc-cmdqd/0: 0% user + 0% kernel
                                                    0% 731/sensors.qcom: 0% user + 0% kernel / faults: 175 minor
                                                    0% 3332/com.miui.securitycenter.remote: 0% user + 0% kernel / faults: 4323 minor
                                                    0% 30979/com.android.quicksearchbox: 0% user + 0% kernel / faults: 447 minor
                                                    0% 16/ksoftirqd/2: 0% user + 0% kernel
                                                    0% 5268/perfd: 0% user + 0% kernel / faults: 319 minor
                                                    0% 31078/kworker/1:0: 0% user + 0% kernel
                                                    0% 4058/android.process.acore: 0% user + 0% kernel / faults: 11386 minor
                                                    0% 5138/com.android.defcontainer: 0% user + 0% kernel / faults: 625 minor
                                                    0% 17604/kworker/0:2H: 0% user + 0% kernel
                                                    0% 10024/com.tencent.mm:push: 0% user + 0% kernel / faults: 1334 minor 7 major
                                                    0% 3444/com.sohu.inputmethod.sogou.xiaomi: 0% user + 0% kernel / faults: 1687 minor
                                                    0% 24/ksoftirqd/4: 0% user + 0% kernel
                                                    0% 11688/android.process.mediaUI: 0% user + 0% kernel / faults: 60 minor
                                                    0% 3035/android.process.media: 0% user + 0% kernel / faults: 835 minor
                                                    0% 11348/kworker/2:1: 0% user + 0% kernel
                                                    0% 3252/com.xiaomi.xmsf: 0% user + 0% kernel / faults: 48 minor
                                                    0% 3515/com.amap.android.location: 0% user + 0% kernel / faults: 62 minor
                                                    0% 21353/com.xiaomi.shop:mishop.push: 0% user + 0% kernel / faults: 649 minor 8 major
                                                    0% 28/ksoftirqd/5: 0% user + 0% kernel
                                                    0% 3619/com.xiaomi.metok
10-10 11:19:39.326 1160-27190/? E/ActivityManager: Error reading /data/anr/traces.txt
                                                   java.io.FileNotFoundException: /data/anr/traces.txt: open failed: ENOENT (No such file or directory)
                                                       at libcore.io.IoBridge.open(IoBridge.java:452)
                                                       at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                       at android.os.FileUtils.readTextFile(FileUtils.java:236)
                                                       at com.android.server.am.ActivityManagerService$18.run(ActivityManagerService.java:12679)
                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                       at libcore.io.Posix.open(Native Method)
                                                       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                       at libcore.io.IoBridge.open(IoBridge.java:438)
                                                       at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                       at android.os.FileUtils.readTextFile(FileUtils.java:236) 
                                                       at com.android.server.am.ActivityManagerService$18.run(ActivityManagerService.java:12679) `

这是产生anr时的错误日志。请大神帮忙看看什么原因？还用能把你的qq号给我吗？好方便请教大神。

**Comment by FDoubleman** [comment]
> E/ActivityManager: ANR in cn.wd.wdstudyonline (cn.wd.wdstudyonline/cn.wdcloud.studyonline.asphone.ui.activity.CourseLearnActivity)
                                                  PID: 17665
                                                  Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 6097.6ms.)
                                                  Load: 7.07 / 6.92 / 6.84
                                                  CPU usage from 856776ms to 0ms ago:
                                                    2.9% 527/adbd: 0.3% user + 2.5% kernel / faults: 110661 minor
                                                    2.6% 441/surfaceflinger: 1.6% user + 1% kernel / faults: 314 minor
                                                    2.2% 1160/system_server: 1.5% user + 0.6% kernel / faults: 26751 minor 6 major
                                                    1.3% 3083/com.android.systemui: 0.9% user + 0.3% kernel / faults: 9266 minor 9 major
                                                    1.2% 285/cfinteractive: 0% user + 1.2% kernel
                                                    0.8% 538/mediaserver: 0.7% user + 0.1% kernel / faults: 89 minor
                                                    0.3% 365/hwrng: 0% user + 0.3% kernel
                                                    0.3% 29795/mdss_fb0: 0% user + 0.3% kernel
                                                    0.2% 26810/com.xiaomi.gamecenter: 0.2% user + 0% kernel / faults: 7444 minor
                                                    0.2% 31150/com.android.browser: 0.2% user + 0% kernel / faults: 23635 minor
                                                    0.2% 386/logd: 0% user + 0.1% kernel / faults: 70 minor
                                                    0.2% 3795/com.android.phone: 0.1% user + 0% kernel / faults: 3234 minor
                                                    0.1% 31192/kworker/u12:8: 0% user + 0.1% kernel
                                                    0.1% 26873/kworker/u12:4: 0% user + 0.1% kernel
                                                    0.1% 7/rcu_preempt: 0% user + 0.1% kernel
                                                    0.1% 45/kworker/u13:0: 0% user + 0.1% kernel
                                                    0.1% 20258/com.tencent.mobileqq:MSF: 0.1% user + 0% kernel / faults: 1738 minor
                                                    0.1% 440/servicemanager: 0% user + 0% kernel / faults: 8 minor
                                                    0.1% 11641/com.xiaomi.market: 0.1% user + 0% kernel / faults: 3128 minor
                                                    0.1% 3031/VosRXThread: 0% user + 0.1% kernel
                                                    0.1% 11734/com.tencent.mobileqq:web: 0% user + 0% kernel / faults: 2124 minor
                                                    0.1% 3030/VosTXThread: 0% user + 0.1% kernel
                                                    0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
                                                    0% 6484/kworker/0:1: 0% user + 0% kernel
                                                    0.1% 3353/wpa_supplicant: 0% user + 0% kernel / faults: 1 minor
                                                    0% 327/irq/412-ft5x46: 0% user + 0% kernel
                                                    0% 3682/com.miui.whetstone: 0% user + 0% kernel / faults: 199 minor
                                                    0% 763/msm_irqbalance: 0% user + 0% kernel / faults: 1 minor
                                                    0% 3274/com.miui.networkassistant.deamon: 0% user + 0% kernel / faults: 365 minor
                                                    0% 5191/irq/215-408000.: 0% user + 0% kernel
                                                    0% 25169/kworker/3:1: 0% user + 0% kernel
                                                    0% 12/ksoftirqd/1: 0% user + 0% kernel
                                                    0% 20/ksoftirqd/3: 0% user + 0% kernel
                                                    0% 68/system: 0% user + 0% kernel
                                                    0% 29801/logcat: 0% user + 0% kernel
                                                    0% 31179/kworker/u12:5: 0% user + 0% kernel
                                                    0% 4607/com.miui.powerkeeper:service: 0% user + 0% kernel / faults: 6293 minor
                                                    0% 3029/VosMCThread: 0% user + 0% kernel
                                                    0% 3361/com.miui.home: 0% user + 0% kernel / faults: 3383 minor 4 major
                                                    0% 551/thermal-engine: 0% user + 0% kernel
                                                    0% 289/mmc-cmdqd/0: 0% user + 0% kernel
                                                    0% 731/sensors.qcom: 0% user + 0% kernel / faults: 175 minor
                                                    0% 3332/com.miui.securitycenter.remote: 0% user + 0% kernel / faults: 4323 minor
                                                    0% 30979/com.android.quicksearchbox: 0% user + 0% kernel / faults: 447 minor
                                                    0% 16/ksoftirqd/2: 0% user + 0% kernel
                                                    0% 5268/perfd: 0% user + 0% kernel / faults: 319 minor
                                                    0% 31078/kworker/1:0: 0% user + 0% kernel
                                                    0% 4058/android.process.acore: 0% user + 0% kernel / faults: 11386 minor
                                                    0% 5138/com.android.defcontainer: 0% user + 0% kernel / faults: 625 minor
                                                    0% 17604/kworker/0:2H: 0% user + 0% kernel
                                                    0% 10024/com.tencent.mm:push: 0% user + 0% kernel / faults: 1334 minor 7 major
                                                    0% 3444/com.sohu.inputmethod.sogou.xiaomi: 0% user + 0% kernel / faults: 1687 minor
                                                    0% 24/ksoftirqd/4: 0% user + 0% kernel
                                                    0% 11688/android.process.mediaUI: 0% user + 0% kernel / faults: 60 minor
                                                    0% 3035/android.process.media: 0% user + 0% kernel / faults: 835 minor
                                                    0% 11348/kworker/2:1: 0% user + 0% kernel
                                                    0% 3252/com.xiaomi.xmsf: 0% user + 0% kernel / faults: 48 minor
                                                    0% 3515/com.amap.android.location: 0% user + 0% kernel / faults: 62 minor
                                                    0% 21353/com.xiaomi.shop:mishop.push: 0% user + 0% kernel / faults: 649 minor 8 major
                                                    0% 28/ksoftirqd/5: 0% user + 0% kernel
                                                    0% 3619/com.xiaomi.metok
10-10 11:19:39.326 1160-27190/? E/ActivityManager: Error reading /data/anr/traces.txt
                                                   java.io.FileNotFoundException: /data/anr/traces.txt: open failed: ENOENT (No such file or directory)
                                                       at libcore.io.IoBridge.open(IoBridge.java:452)
                                                       at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                       at android.os.FileUtils.readTextFile(FileUtils.java:236)
                                                       at com.android.server.am.ActivityManagerService$18.run(ActivityManagerService.java:12679)
                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                       at libcore.io.Posix.open(Native Method)
                                                       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                       at libcore.io.IoBridge.open(IoBridge.java:438)
                                                       at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                       at android.os.FileUtils.readTextFile(FileUtils.java:236) 
                                                       at com.android.server.am.ActivityManagerService$18.run(ActivityManagerService.java:12679)

**Comment by FDoubleman** [comment]
@tcking 这是产生anr时的错误日志。请大神帮忙看看什么原因？还用能把你的qq号给我吗？好方便请教大神。

**Comment by tcking** [comment]
看下`traces.txt`是否有堆栈信息，执行`adb pull data/anr/traces.txt 目标目录`把traces.txt拉到电脑上然后贴出来看看
